name: CI-CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

          script: |
            if [ ! -d "cicd-myapp" ]; then
              git clone https://github.com/samsonprincer-DS/cicd-myapp.git
            fi

            cd cicd-myapp

            git config --global --add safe.directory /home/ubuntu/cicd-myapp

            sudo chown -R ubuntu:ubuntu /home/ubuntu/cicd-myapp

            git fetch --all
            git reset --hard origin/main

            docker stop cicd-myapp || true
            docker rm cicd-myapp || true
            docker rmi cicd-myapp || true

            docker build -t cicd-myapp .

            docker run -d -p 80:80 --restart always --name cicd-myapp cicd-myapp
