name: CI-CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

          script: |
            if [ ! -d "myapp" ]; then
            git clone https://github.com/samsonprincer-DS/cicd-myapp.git
            fi

            cd myapp

            git config --global --add safe.directory /home/ubuntu/myapp

              sudo chown -R ubuntu:ubuntu /home/ubuntu/myapp

            git fetch --all
            git reset --hard origin/main
          
                docker stop myapp || true
                docker rm myapp || true
                docker rmi myapp || true
              
                docker build -t myapp .
              
                docker run -d -p 80:80 --restart always --name myapp myapp
